/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ColchonC;
import Controlador.Conexion;
import Modelo.Esponja;
import Modelo.Medidas;
import com.sun.corba.se.spi.logging.CORBALogDomains;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author juanki
 */
public class NuevoProductoV extends javax.swing.JFrame {
    EsponjaV vistaEsponja;
    MedidasV vistaMedidas;
    private ColchonC colchon;
    private String nombre;
    private String color;
    private String tela;
    private String tipo;
    private Esponja esponja;
    private Medidas medidas;
    private ArrayList<Esponja> listaEsponjas;
    private ArrayList<Medidas> listaMedidas;
    private Conexion util=new Conexion();
    private TransaccionV transaccion;
    public NuevoProductoV() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        colchon =new ColchonC();
        actualizar();
    }

    NuevoProductoV(TransaccionV aThis) {
        transaccion=aThis;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        colchon =new ColchonC();
        actualizar();
        valoresPorDefecto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();
        jComboBoxEsponja = new javax.swing.JComboBox();
        jComboBoxTela = new javax.swing.JComboBox();
        jComboBoxColor = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMedidas = new javax.swing.JComboBox();
        jButtonVistaMedidas = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jButtonVistaEsponja = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buttonActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonVer = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(283, 260));
        jPanel1.setLayout(null);

        jLabel2.setText("Color");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 112, 50, 16);

        jLabel3.setText("Tela");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 138, 40, 16);

        jLabel4.setText("Esponja");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 165, 50, 16);

        jLabel5.setText("Tipo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 193, 40, 16);

        jComboBoxTipo.setEditable(true);
        jPanel1.add(jComboBoxTipo);
        jComboBoxTipo.setBounds(77, 190, 125, 27);

        jComboBoxEsponja.setEditable(true);
        jPanel1.add(jComboBoxEsponja);
        jComboBoxEsponja.setBounds(77, 162, 125, 27);

        jComboBoxTela.setEditable(true);
        jPanel1.add(jComboBoxTela);
        jComboBoxTela.setBounds(77, 135, 125, 27);

        jComboBoxColor.setEditable(true);
        jPanel1.add(jComboBoxColor);
        jComboBoxColor.setBounds(77, 109, 125, 27);

        jLabel6.setText("Medidas");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 220, 50, 16);

        jComboBoxMedidas.setEditable(true);
        jPanel1.add(jComboBoxMedidas);
        jComboBoxMedidas.setBounds(77, 217, 125, 27);

        jButtonVistaMedidas.setText("+");
        jButtonVistaMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVistaMedidasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVistaMedidas);
        jButtonVistaMedidas.setBounds(208, 216, 35, 28);

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar);
        botonGuardar.setBounds(40, 271, 100, 28);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar);
        botonCancelar.setBounds(149, 271, 90, 28);

        jButtonVistaEsponja.setText("+");
        jButtonVistaEsponja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVistaEsponjaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVistaEsponja);
        jButtonVistaEsponja.setBounds(208, 161, 35, 28);

        jLabel7.setText("Producto Colchon");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 22, 110, 16);

        buttonActualizar.setText("Actualizar");
        buttonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonActualizar);
        buttonActualizar.setBounds(20, 54, 90, 28);

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color", "Tela", "Esponja", "Medidas", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(267, 29, 456, 265);

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 86, 50, 16);
        jPanel1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(75, 83, 127, 27);

        jButtonVer.setText("Ver");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVer);
        jButtonVer.setBounds(330, 300, 77, 28);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar);
        jButtonEliminar.setBounds(430, 300, 90, 28);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 300, 100, 28);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 1680, 1050);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if(validar()){
            colchon= new Controlador.ColchonC(this);
            colchon.guardar();
            limpiarCampos();
            limpiarTabla();
            llenarjTableProductos();//transaccion.setProducto(colchon.get);
        }
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void jButtonVistaMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVistaMedidasActionPerformed
        vistaMedidas = new MedidasV(this);
        vistaMedidas.setVisible(true);
    }//GEN-LAST:event_jButtonVistaMedidasActionPerformed

    private void jButtonVistaEsponjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVistaEsponjaActionPerformed
        vistaEsponja= new EsponjaV(this);
        vistaEsponja.setVisible(true);
    }//GEN-LAST:event_jButtonVistaEsponjaActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_buttonActualizarActionPerformed

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        if(evt.getClickCount()==2){
            transaccion.setProductoSeleccionado(jTableProductos.getModel().getValueAt(filaSeleccionada(),0));
            dispose();
        }
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        editarProducto();
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        eliminarProducto();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modificarProducto();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProductoV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JButton jButtonVistaEsponja;
    private javax.swing.JButton jButtonVistaMedidas;
    private javax.swing.JComboBox jComboBoxColor;
    private javax.swing.JComboBox jComboBoxEsponja;
    private javax.swing.JComboBox jComboBoxMedidas;
    private javax.swing.JComboBox jComboBoxTela;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    private boolean validar() {
        System.out.println(jComboBoxEsponja.getSelectedIndex()+"indice");
        if(jComboBoxEsponja.getSelectedIndex()>=0)
            esponja=colchon.getListaEsponjas().get(jComboBoxEsponja.getSelectedIndex());
        else
            esponja=null;
        medidas=colchon.getListaMedidas().get(jComboBoxMedidas.getSelectedIndex());
        tela = jComboBoxTela.getSelectedItem().toString();
        color = jComboBoxColor.getSelectedItem().toString();
        tipo = jComboBoxTipo.getSelectedItem().toString();
        nombre = jTextFieldNombre.getText();
        return true;
    }
    private void llenarListaMedias(){
        colchon.llenarListaMedidas(this.jComboBoxMedidas);
        AutoCompleteDecorator.decorate(jComboBoxMedidas);
    }
    
    private void llenarListaEsponjas(){
        colchon.llenarListaEsponjas(this.jComboBoxEsponja);
        AutoCompleteDecorator.decorate(jComboBoxEsponja);
    }
    
    /**
     * @return the producto
     */
    public ColchonC getProducto() {
        return colchon;
    }

    /**
     * @param producto the producto to set
     */
    public void setProducto(ColchonC producto) {
        this.colchon = producto;
    }

    /**
     * @return the color
     */
    public String getColor() {
        return color;
    }

    /**
     * @param color the color to set
     */
    public void setColor(String color) {
        this.color = color;
        jComboBoxColor.setSelectedItem(color);
    }

    /**
     * @return the tela
     */
    public String getTela() {
        return tela;
    }

    /**
     * @param tela the tela to set
     */
    public void setTela(String tela) {
        this.tela = tela;
        jComboBoxTela.setSelectedItem(tela);
    }

    /**
     * @return the tipo
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * @param tipo the tipo to set
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
        jComboBoxTipo.setSelectedItem(tipo);
    }

    /**
     * @return the esponja
     */
    public Esponja getEsponja() {
        return esponja;
    }

    /**
     * @param esponja the esponja to set
     */
    public void setEsponja(Esponja esponja) {
        this.esponja = esponja;
        jComboBoxEsponja.setSelectedItem(esponja.getCodigo());
    }

    /**
     * @return the medidas
     */
    public Medidas getMedidas() {
        return medidas;
    }

    /**
     * @param medidas the medidas to set
     */
    public void setMedidas(Medidas medidas) {
        this.medidas = medidas;
        jComboBoxMedidas.setSelectedItem(medidas.getCodigo());
    }

    /**
     * @return the listaEsponjas
     */
    public ArrayList<Esponja> getListaEsponjas() {
        return listaEsponjas;
    }

    /**
     * @param listaEsponjas the listaEsponjas to set
     */
    public void setListaEsponjas(ArrayList<Esponja> listaEsponjas) {
        this.listaEsponjas = listaEsponjas;
    }

    /**
     * @return the listaMedidas
     */
    public ArrayList<Medidas> getListaMedidas() {
        return listaMedidas;
    }

    /**
     * @param listaMedidas the listaMedidas to set
     */
    public void setListaMedidas(ArrayList<Medidas> listaMedidas) {
        this.listaMedidas = listaMedidas;
    }

    private void inicializarVariables() {
        llenarListaMedias();
        llenarListaEsponjas();
        llenarjTableProductos();
        llenarAtributosColchon();
    }

    private void actualizar() {
        limpiarTabla();
        llenarListaMedias();
        llenarListaEsponjas();
        llenarjTableProductos();
        llenarAtributosColchon();
        limpiarCampos();
    }

    private void limpiarTabla(){
        DefaultTableModel dm=(DefaultTableModel)jTableProductos.getModel();
        for(int tam=dm.getRowCount()-1;tam>=0;tam--){
            dm.removeRow(tam);
        }
    }
    
    private void llenarjTableProductos() {
        colchon.llenarJTableProductos(jTableProductos);
    }

    private void llenarAtributosColchon() {
        colchon.llenarAtributosColchon(this.jComboBoxColor,this.jComboBoxTela,this.jComboBoxTipo);
        AutoCompleteDecorator.decorate(jComboBoxColor);
        AutoCompleteDecorator.decorate(jComboBoxTela);
        AutoCompleteDecorator.decorate(jComboBoxTipo);
    }

    private void limpiarCampos() {
        jComboBoxColor.setSelectedItem("");
        jComboBoxEsponja.setSelectedItem("");
        jComboBoxMedidas.setSelectedItem("");
        jComboBoxTela.setSelectedItem("");
        jComboBoxTipo.setSelectedItem("");
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
        jTextFieldNombre.setText(nombre);
    }
     public int filaSeleccionada(){
        int fila_select = jTableProductos.getSelectedRow();
        if(fila_select<0)
            JOptionPane.showMessageDialog(this,"Seleccione una Esponja");
        return fila_select;
    }

    void setMedidasSeleccionada(Object medidas) {
        llenarListaMedias();
        jComboBoxMedidas.setSelectedItem(medidas);
    }

    void setEsponjaSeleccionada(Object valueAt) {
        llenarListaEsponjas();
        jComboBoxEsponja.setSelectedItem(valueAt);
    }

    private void editarProducto() {
        if(filaSeleccionada()>=0){
            colchon.establecerProductoIndex(filaSeleccionada());
            colchon.getProducto(this);
        }
    }

    private void eliminarProducto() {
        
        if(filaSeleccionada()>=0){
            colchon.establecerProductoIndex(filaSeleccionada());
            if(!colchon.eliminarProducto())
                JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar, la producto esta relacionado");
        }
        
        actualizar();
    }

    private void modificarProducto() {
        if(validar()){
        colchon.setProducto(this);    
        colchon.modificar();
        }
        actualizar();
    }

    private void valoresPorDefecto() {
        jTextFieldNombre.setText("Auto");
    }
    
       
}
