/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;
import Modelo.Colchon;
import Controlador.TransaccionC;
import Controlador.Util;
import Controlador.Validacion;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author juanki
 */
public class TransaccionV extends javax.swing.JFrame {

    /**
     * Creates new form Transaccion2
     */
    private Util util=new Util();
    private TransaccionC transaccion=new TransaccionC();
    private String codigo;
    private boolean tipo;
    private Date fecha;
    private String detalle;
    private Double precioUnitario;
    private Double costoUnitario;
    private Double cantidad;
    private Double precioCosto;
    private Double precioMayor;
    private int idProducto;
    private Colchon producto;
    private Modelo.Deposito deposito;
    private Validacion validacion;
    private Menu menu;
    public TransaccionV(Menu menu) {
        initComponents();
        iniciarComponentes();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.menu=menu;
        actualizar();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDetalle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPrecioUnitario = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPrecioMayor = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jComboBoxProducto = new javax.swing.JComboBox();
        jRadioButtonEntrada = new javax.swing.JRadioButton();
        jRadioButtonSalida = new javax.swing.JRadioButton();
        jTextFieldPrecioCosto = new javax.swing.JTextField();
        jButtonAddProducto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCostoUnitario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDepositos = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Transaccion");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 90, 16);

        jLabel2.setText("Producto");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 60, 16);

        jLabel4.setText("Fecha");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 50, 40, 16);

        jTextFieldDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDetalleActionPerformed(evt);
            }
        });
        jTextFieldDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDetalleKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldDetalle);
        jTextFieldDetalle.setBounds(100, 300, 310, 27);

        jLabel5.setText("Detalle");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 300, 50, 24);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Precio Unitario");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 210, 90, 16);

        jLabel7.setText("Cantidad");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 180, 70, 16);

        jTextFieldPrecioUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioUnitarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioUnitarioKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldPrecioUnitario);
        jTextFieldPrecioUnitario.setBounds(290, 210, 86, 27);

        jTextFieldCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCantidad);
        jTextFieldCantidad.setBounds(100, 180, 86, 27);

        jLabel8.setText("Codigo");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 50, 60, 16);

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(100, 50, 91, 27);
        jPanel1.add(jDateChooser);
        jDateChooser.setBounds(280, 50, 127, 24);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio Mayor");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 240, 80, 16);

        jTextFieldPrecioMayor.setEditable(false);
        jTextFieldPrecioMayor.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldPrecioMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMayorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPrecioMayor);
        jTextFieldPrecioMayor.setBounds(290, 240, 87, 27);

        jButtonGuardar.setMnemonic('g');
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar);
        jButtonGuardar.setBounds(150, 340, 90, 28);

        jButtonCancelar.setMnemonic('c');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(250, 340, 100, 28);

        jButtonAceptar.setMnemonic('a');
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar);
        jButtonAceptar.setBounds(50, 340, 90, 28);

        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxProducto);
        jComboBoxProducto.setBounds(100, 80, 130, 26);

        jRadioButtonEntrada.setText("Entrada");
        jPanel1.add(jRadioButtonEntrada);
        jRadioButtonEntrada.setBounds(20, 150, 70, 18);

        jRadioButtonSalida.setText("Salida");
        jPanel1.add(jRadioButtonSalida);
        jRadioButtonSalida.setBounds(100, 150, 70, 18);

        jTextFieldPrecioCosto.setEditable(false);
        jTextFieldPrecioCosto.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextFieldPrecioCosto);
        jTextFieldPrecioCosto.setBounds(100, 240, 86, 27);

        jButtonAddProducto.setMnemonic('d');
        jButtonAddProducto.setText("add");
        jButtonAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddProducto);
        jButtonAddProducto.setBounds(240, 80, 49, 28);

        jLabel10.setText("PrecioCosto");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 240, 70, 16);

        jLabel11.setText("Costo Unitario");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 210, 90, 16);

        jTextFieldCostoUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCostoUnitarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostoUnitarioKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCostoUnitario);
        jTextFieldCostoUnitario.setBounds(100, 210, 86, 27);

        jLabel3.setText("Deposito");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 60, 16);

        jComboBoxDepositos.setEditable(true);
        jPanel1.add(jComboBoxDepositos);
        jComboBoxDepositos.setBounds(100, 110, 130, 28);

        jButton2.setMnemonic('d');
        jButton2.setText("add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(240, 110, 49, 28);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(fondo);
        fondo.setBounds(-250, -30, 1730, 1050);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDetalleActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductoActionPerformed
        ProductosV np=new ProductosV(this);
        np.setVisible(true);
    }//GEN-LAST:event_jButtonAddProductoActionPerformed

    private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProductoActionPerformed

    private void jTextFieldPrecioMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMayorActionPerformed

    private void jTextFieldCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKeyTyped
        validacion.validacionesSoloNumeros(evt);
    }//GEN-LAST:event_jTextFieldCantidadKeyTyped

    private void jTextFieldCostoUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostoUnitarioKeyTyped
        validacion.validacionesSoloNumeros(evt);
        
    }//GEN-LAST:event_jTextFieldCostoUnitarioKeyTyped

    private void jTextFieldPrecioUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioUnitarioKeyTyped
        validacion.validacionesSoloNumeros(evt);
        
    }//GEN-LAST:event_jTextFieldPrecioUnitarioKeyTyped

    private void jTextFieldDetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDetalleKeyTyped
       validacion.validacionCantidadCaracteres(jTextFieldDetalle.getText(), 300, evt);
    }//GEN-LAST:event_jTextFieldDetalleKeyTyped

    private void jTextFieldCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKeyReleased
        calularTotalPrecioMayoro();
        calularTotalPrecioCosto();
    }//GEN-LAST:event_jTextFieldCantidadKeyReleased

    private void jTextFieldCostoUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostoUnitarioKeyReleased
        calularTotalPrecioCosto();
    }//GEN-LAST:event_jTextFieldCostoUnitarioKeyReleased

    private void jTextFieldPrecioUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioUnitarioKeyReleased
        calularTotalPrecioMayoro();
    }//GEN-LAST:event_jTextFieldPrecioUnitarioKeyReleased

    private void jTextFieldCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyReleased
        validacion.esVacioJTextField(jTextFieldCodigo);
    }//GEN-LAST:event_jTextFieldCodigoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DepositoV dep=new DepositoV();
        dep.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaccionV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaccionV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaccionV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaccionV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaccionV().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAddProducto;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox jComboBoxDepositos;
    private javax.swing.JComboBox jComboBoxProducto;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonEntrada;
    private javax.swing.JRadioButton jRadioButtonSalida;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCostoUnitario;
    private javax.swing.JTextField jTextFieldDetalle;
    private javax.swing.JTextField jTextFieldPrecioCosto;
    private javax.swing.JTextField jTextFieldPrecioMayor;
    private javax.swing.JTextField jTextFieldPrecioUnitario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the transaccion
     */
    public TransaccionC getTransaccion() {
        return transaccion;
    }

    /**
     * @param transaccion the transaccion to set
     */
    public void setTransaccion(TransaccionC transaccion) {
        this.transaccion = transaccion;
    }

    /**
     * @return the codigo
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
        jTextFieldCodigo.setText(codigo);
    }

    /**
     * @return the tipo
     */
    public boolean isTipo() {
        return tipo;
    }

    /**
     * @param tipo the tipo to set
     */
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
        if(tipo)
            jRadioButtonEntrada.setSelected(true);
        else
            jRadioButtonSalida.setSelected(true);
    }

    /**
     * @return the fecha
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * @param fecha the fecha to set
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
        jDateChooser.setDate(fecha);
    }

    /**
     * @return the detalle
     */
    public String getDetalle() {
        return detalle;
    }

    /**
     * @param detalle the detalle to set
     */
    public void setDetalle(String detalle) {
        this.detalle = detalle;
        jTextFieldDetalle.setText(detalle.toString());
    }

    /**
     * @return the precioUnitario
     */
    public Double getPrecioUnitario() {
        return precioUnitario;
    }

    /**
     * @param precioUnitario the precioUnitario to set
     */
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
        jTextFieldPrecioUnitario.setText(precioUnitario.toString());
    }

    /**
     * @return the cantidad
     */
    public Double getCantidad() {
        return cantidad;
    }

    /**
     * @param cantidad the cantidad to set
     */
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
        jTextFieldCantidad.setText(cantidad.toString());
    }

    /**
     * @return the precioCosto
     */
    public Double getPrecioCosto() {
        return precioCosto;
    }

    /**
     * @param precioCosto the precioCosto to set
     */
    public void setPrecioCosto(Double precioCosto) {
        this.precioCosto = precioCosto;
        jTextFieldPrecioCosto.setText(precioCosto.toString());
    }

    /**
     * @return the precioMayor
     */
    public Double getPrecioMayor() {
        return precioMayor;
    }

    /**
     * @param precioMayor the precioMayor to set
     */
    public void setPrecioMayor(Double precioMayor) {
        this.precioMayor = precioMayor;
        jTextFieldPrecioMayor.setText(precioMayor.toString());
    }

    /**
     * @return the idProducto
     */
    public int getIdProducto() {
        return idProducto;
    }

    /**
     * @param idProducto the idProducto to set
     */
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }

    private void guardar() {
        if(validar()){
            transaccion.guardar(this);
            transaccion.guardar();
            menu.actualizar();
            dispose();
        }        
    }

    private boolean validar() {
        boolean res;
        if(!validacion.esVacioJTextField(jTextFieldCodigo)){
            if(!validacion.esVacioJTextField(jTextFieldPrecioUnitario)){
                if(!validacion.esVacioJTextField(jTextFieldCostoUnitario)){
                    if(isEntrada()){                        
                        codigo=jTextFieldCodigo.getText();
                        tipo=isEntrada();
                        fecha=jDateChooser.getDate();
                        detalle=jTextFieldDetalle.getText();
                        precioUnitario=Double.parseDouble(jTextFieldPrecioUnitario.getText());
                        costoUnitario=Double.parseDouble(jTextFieldCostoUnitario.getText());
                        cantidad=Double.parseDouble(jTextFieldCantidad.getText());
                        precioCosto=Double.parseDouble(jTextFieldPrecioCosto.getText());
                        precioMayor=Double.parseDouble(jTextFieldPrecioMayor.getText());
                        producto=transaccion.getListaProductos().get(jComboBoxProducto.getSelectedIndex());
                        deposito=transaccion.getListaDepositos().get(jComboBoxDepositos.getSelectedIndex());
                        res= true;
                    }else{
                        validarSalida();
                        res= true;
                    }
                }else{
                    res=false;
                    validacion.mostrarMensaje("debe introducir el costo unitario");
                }
            }else{
                res=false;
                validacion.mostrarMensaje("debe introducir el precio unitario");
            }
        }else{
            res=false;
            validacion.mostrarMensaje("debe introducir el codigo de la transaccion");
        }
        return res;
    }
    
    private void actualizar() {
        llenarListaProductos();
        llenarListaDepositos();
    }
    private void llenarListaProductos(){
        transaccion.llenarListaProductos(jComboBoxProducto);
    }

    private void iniciarComponentes() {
        jDateChooser.setDate(new Date());
        buttonGroupTipo.add(jRadioButtonEntrada);
        buttonGroupTipo.add(jRadioButtonSalida);
        validacion=new Validacion();
        validacion.esVacioJTextField(jTextFieldCodigo);
        validacion.esVacioJTextField(jTextFieldCantidad);
        validacion.esVacioJTextField(jTextFieldCostoUnitario);
        validacion.esVacioJTextField(jTextFieldPrecioUnitario);
    }

    private boolean isEntrada() {
        if(jRadioButtonEntrada.isSelected())
            return true;
        else
            return false;
    }

    /**
     * @return the producto
     */
    public Colchon getProducto() {
        return producto;
    }

    /**
     * @param producto the producto to set
     */
    public void setProducto(Colchon producto) {
        this.producto = producto;
        jComboBoxProducto.setSelectedItem(producto.getNombre());
    }

    void setProductoSeleccionado(Object algo) {
        actualizar();
        jComboBoxProducto.setSelectedItem(algo);
    }

    /**
     * @return the costoUnitario
     */
    public Double getCostoUnitario() {
        return costoUnitario;
    }

    /**
     * @param costoUnitario the costoUnitario to set
     */
    public void setCostoUnitario(Double costoUnitario) {
        this.costoUnitario = costoUnitario;
        jTextFieldCostoUnitario.setText(costoUnitario.toString());
    }

    private void llenarListaDepositos() {
        transaccion.llenarListaDepositos(jComboBoxDepositos);
    }

    /**
     * @return the deposito
     */
    public Modelo.Deposito getDeposito() {
        return deposito;
    }

    /**
     * @param deposito the deposito to set
     */
    public void setDeposito(Modelo.Deposito deposito) {
        this.deposito = deposito;
    }
    
    private void calularTotalPrecioMayoro(){
        if(!(validacion.esVacioJTextField(jTextFieldCantidad))&&!(validacion.esVacioJTextField(jTextFieldPrecioUnitario)))
            jTextFieldPrecioMayor.setText(""+(Integer.parseInt(jTextFieldPrecioUnitario.getText()))*(Integer.parseInt(jTextFieldCantidad.getText())));
        else
            jTextFieldPrecioMayor.setText("");
    }
    private void calularTotalPrecioCosto(){
        if(!(validacion.esVacioJTextField(jTextFieldCantidad))&&!(validacion.esVacioJTextField(jTextFieldCostoUnitario)))
            jTextFieldPrecioCosto.setText(""+(Integer.parseInt(jTextFieldCostoUnitario.getText()))*(Integer.parseInt(jTextFieldCantidad.getText())));
        else
            jTextFieldPrecioCosto.setText("");
    }

    private void validarSalida() {
        validarSalidaPEPS();
    }

    private void validarSalidaPEPS() {
        
    }

    
}
