package Modelo;
// Generated Feb 21, 2014 9:02:18 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Colchon generated by hbm2java
 */
public class Colchon  implements java.io.Serializable {


     private Integer id;
     private Esponja esponja;
     private Medidas medidas;
     private String nombre;
     private String color;
     private String tela;
     private String tipo;
     private Set transaccions = new HashSet(0);

    public Colchon() {
    }

    public Colchon(Esponja esponja, Medidas medidas, String nombre, String color, String tela, String tipo, Set transaccions) {
       this.esponja = esponja;
       this.medidas = medidas;
       this.nombre = nombre;
       this.color = color;
       this.tela = tela;
       this.tipo = tipo;
       this.transaccions = transaccions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Esponja getEsponja() {
        return this.esponja;
    }
    
    public void setEsponja(Esponja esponja) {
        this.esponja = esponja;
    }
    public Medidas getMedidas() {
        return this.medidas;
    }
    
    public void setMedidas(Medidas medidas) {
        this.medidas = medidas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getTela() {
        return this.tela;
    }
    
    public void setTela(String tela) {
        this.tela = tela;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set transaccions) {
        this.transaccions = transaccions;
    }




}


