package Modelo;
// Generated Aug 3, 2014 10:33:50 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Deposito generated by hbm2java
 */
public class Deposito  implements java.io.Serializable {


     private int iddeposito;
     private String nombredeposito;
     private String direccion;
     private String detalledeposito;
     private Set entradas = new HashSet(0);

    public Deposito() {
    }

	
    public Deposito(int iddeposito) {
        this.iddeposito = iddeposito;
    }
    public Deposito(int iddeposito, String nombredeposito, String direccion, String detalledeposito, Set entradas) {
       this.iddeposito = iddeposito;
       this.nombredeposito = nombredeposito;
       this.direccion = direccion;
       this.detalledeposito = detalledeposito;
       this.entradas = entradas;
    }
   
    public int getIddeposito() {
        return this.iddeposito;
    }
    
    public void setIddeposito(int iddeposito) {
        this.iddeposito = iddeposito;
    }
    public String getNombredeposito() {
        return this.nombredeposito;
    }
    
    public void setNombredeposito(String nombredeposito) {
        this.nombredeposito = nombredeposito;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDetalledeposito() {
        return this.detalledeposito;
    }
    
    public void setDetalledeposito(String detalledeposito) {
        this.detalledeposito = detalledeposito;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


