package Modelo;
// Generated 08-feb-2014 17:42:54 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Deposito generated by hbm2java
 */
public class Deposito  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String detalle;
     private Set transaccions = new HashSet(0);

    public Deposito() {
    }

    public Deposito(String nombre, String detalle, Set transaccions) {
       this.nombre = nombre;
       this.detalle = detalle;
       this.transaccions = transaccions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Set getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set transaccions) {
        this.transaccions = transaccions;
    }




}


