package Modelo;
// Generated 08-feb-2014 17:42:54 by Hibernate Tools 3.6.0



/**
 * Dobleacolchado generated by hbm2java
 */
public class Dobleacolchado  implements java.io.Serializable {


     private Integer id;
     private String tipo;
     private String altura;
     private Boolean movible;

    public Dobleacolchado() {
    }

    public Dobleacolchado(String tipo, String altura, Boolean movible) {
       this.tipo = tipo;
       this.altura = altura;
       this.movible = movible;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getAltura() {
        return this.altura;
    }
    
    public void setAltura(String altura) {
        this.altura = altura;
    }
    public Boolean getMovible() {
        return this.movible;
    }
    
    public void setMovible(Boolean movible) {
        this.movible = movible;
    }




}


