package Modelo;
// Generated May 5, 2014 12:01:48 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private Integer id;
     private Colchon colchon;
     private Deposito deposito;
     private String codigo;
     private Boolean tipo;
     private Date fecha;
     private String detalle;
     private Double cantidad;
     private Double costoUnitario;
     private Double precioUnitario;
     private Double totalCosto;
     private Double totalMayor;
     private Double stok;
     private Set relacionentradasalidas = new HashSet(0);

    public Entrada() {
    }

	
    public Entrada(Colchon colchon, Deposito deposito) {
        this.colchon = colchon;
        this.deposito = deposito;
    }
    public Entrada(Colchon colchon, Deposito deposito, String codigo, Boolean tipo, Date fecha, String detalle, Double cantidad, Double costoUnitario, Double precioUnitario, Double totalCosto, Double totalMayor, Double stok, Set relacionentradasalidas) {
       this.colchon = colchon;
       this.deposito = deposito;
       this.codigo = codigo;
       this.tipo = tipo;
       this.fecha = fecha;
       this.detalle = detalle;
       this.cantidad = cantidad;
       this.costoUnitario = costoUnitario;
       this.precioUnitario = precioUnitario;
       this.totalCosto = totalCosto;
       this.totalMayor = totalMayor;
       this.stok = stok;
       this.relacionentradasalidas = relacionentradasalidas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Colchon getColchon() {
        return this.colchon;
    }
    
    public void setColchon(Colchon colchon) {
        this.colchon = colchon;
    }
    public Deposito getDeposito() {
        return this.deposito;
    }
    
    public void setDeposito(Deposito deposito) {
        this.deposito = deposito;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Boolean getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Boolean tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public Double getCostoUnitario() {
        return this.costoUnitario;
    }
    
    public void setCostoUnitario(Double costoUnitario) {
        this.costoUnitario = costoUnitario;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Double getTotalCosto() {
        return this.totalCosto;
    }
    
    public void setTotalCosto(Double totalCosto) {
        this.totalCosto = totalCosto;
    }
    public Double getTotalMayor() {
        return this.totalMayor;
    }
    
    public void setTotalMayor(Double totalMayor) {
        this.totalMayor = totalMayor;
    }
    public Double getStok() {
        return this.stok;
    }
    
    public void setStok(Double stok) {
        this.stok = stok;
    }
    public Set getRelacionentradasalidas() {
        return this.relacionentradasalidas;
    }
    
    public void setRelacionentradasalidas(Set relacionentradasalidas) {
        this.relacionentradasalidas = relacionentradasalidas;
    }




}


