package Modelo;
// Generated Aug 31, 2014 8:32:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Esponja generated by hbm2java
 */
public class Esponja  implements java.io.Serializable {


     private int idesponja;
     private String material;
     private String coloresponja;
     private String codigoesponja;
     private Set colchons = new HashSet(0);

    public Esponja() {
    }

	
    public Esponja(int idesponja) {
        this.idesponja = idesponja;
    }
    public Esponja(int idesponja, String material, String coloresponja, String codigoesponja, Set colchons) {
       this.idesponja = idesponja;
       this.material = material;
       this.coloresponja = coloresponja;
       this.codigoesponja = codigoesponja;
       this.colchons = colchons;
    }
   
    public int getIdesponja() {
        return this.idesponja;
    }
    
    public void setIdesponja(int idesponja) {
        this.idesponja = idesponja;
    }
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    public String getColoresponja() {
        return this.coloresponja;
    }
    
    public void setColoresponja(String coloresponja) {
        this.coloresponja = coloresponja;
    }
    public String getCodigoesponja() {
        return this.codigoesponja;
    }
    
    public void setCodigoesponja(String codigoesponja) {
        this.codigoesponja = codigoesponja;
    }
    public Set getColchons() {
        return this.colchons;
    }
    
    public void setColchons(Set colchons) {
        this.colchons = colchons;
    }




}


