package Modelo;
// Generated 08-feb-2014 17:42:54 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Medidas generated by hbm2java
 */
public class Medidas  implements java.io.Serializable {


     private Integer id;
     private String ancho;
     private String largo;
     private String grosor;
     private String plazas;
     private String codigo;
     private Set colchons = new HashSet(0);

    public Medidas() {
    }

    public Medidas(String ancho, String largo, String grosor, String plazas, String codigo, Set colchons) {
       this.ancho = ancho;
       this.largo = largo;
       this.grosor = grosor;
       this.plazas = plazas;
       this.codigo = codigo;
       this.colchons = colchons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAncho() {
        return this.ancho;
    }
    
    public void setAncho(String ancho) {
        this.ancho = ancho;
    }
    public String getLargo() {
        return this.largo;
    }
    
    public void setLargo(String largo) {
        this.largo = largo;
    }
    public String getGrosor() {
        return this.grosor;
    }
    
    public void setGrosor(String grosor) {
        this.grosor = grosor;
    }
    public String getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(String plazas) {
        this.plazas = plazas;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getColchons() {
        return this.colchons;
    }
    
    public void setColchons(Set colchons) {
        this.colchons = colchons;
    }




}


