package Modelo;
// Generated May 5, 2014 12:01:48 PM by Hibernate Tools 3.6.0



/**
 * Relacionentradasalida generated by hbm2java
 */
public class Relacionentradasalida  implements java.io.Serializable {


     private Integer id;
     private Entrada entrada;
     private Salida salida;
     private Double cantidad;

    public Relacionentradasalida() {
    }

	
    public Relacionentradasalida(Entrada entrada, Salida salida) {
        this.entrada = entrada;
        this.salida = salida;
    }
    public Relacionentradasalida(Entrada entrada, Salida salida, Double cantidad) {
       this.entrada = entrada;
       this.salida = salida;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }
    public Salida getSalida() {
        return this.salida;
    }
    
    public void setSalida(Salida salida) {
        this.salida = salida;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }




}


