package Modelo;
// Generated May 6, 2014 10:27:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salida generated by hbm2java
 */
public class Salida  implements java.io.Serializable {


     private Integer id;
     private Colchon colchon;
     private Double cantidad;
     private Date fecha;
     private String detalle;
     private Set relacionentradasalidas = new HashSet(0);

    public Salida() {
    }

	
    public Salida(Colchon colchon) {
        this.colchon = colchon;
    }
    public Salida(Colchon colchon, Double cantidad, Date fecha, String detalle, Set relacionentradasalidas) {
       this.colchon = colchon;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.detalle = detalle;
       this.relacionentradasalidas = relacionentradasalidas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Colchon getColchon() {
        return this.colchon;
    }
    
    public void setColchon(Colchon colchon) {
        this.colchon = colchon;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Set getRelacionentradasalidas() {
        return this.relacionentradasalidas;
    }
    
    public void setRelacionentradasalidas(Set relacionentradasalidas) {
        this.relacionentradasalidas = relacionentradasalidas;
    }




}


