package Modelo;
// Generated 28-oct-2014 11:47:39 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salida generated by hbm2java
 */
public class Salida  implements java.io.Serializable {
    
     private int idsalida;
     private Colchon colchon;
     private Date fechasalida;
     private BigDecimal cantidadsalida;
     private String detallesalida;
     private Set relacionentradasalidas = new HashSet(0);

    public Salida() {
    }

	
    public Salida(int idsalida) {
        this.idsalida = idsalida;
    }
   
    public Salida(int idsalida, Colchon colchon, Date fechasalida, BigDecimal cantidadsalida, String detallesalida, Set relacionentradasalidas) {
       this.idsalida = idsalida;
       this.colchon = colchon;
       this.fechasalida = fechasalida;
       this.cantidadsalida = cantidadsalida;
       this.detallesalida = detallesalida;
       this.relacionentradasalidas = relacionentradasalidas;
    }
   
    public int getIdsalida() {
        return this.idsalida;
    }
    
    public void setIdsalida(int idsalida) {
        this.idsalida = idsalida;
    }
    
    public Colchon getColchon() {
        return this.colchon;
    }
    
    public void setColchon(Colchon colchon) {
        this.colchon = colchon;
    }
    public Date getFechasalida() {
        return this.fechasalida;
    }
    
    public void setFechasalida(Date fechasalida) {
        this.fechasalida = fechasalida;
    }
    public BigDecimal getCantidadsalida() {
        return this.cantidadsalida;
    }
    
    public void setCantidadsalida(BigDecimal cantidadsalida) {
        this.cantidadsalida = cantidadsalida;
    }
    public String getDetallesalida() {
        return this.detallesalida;
    }
    
    public void setDetallesalida(String detallesalida) {
        this.detallesalida = detallesalida;
    }
    public Set getRelacionentradasalidas() {
        return this.relacionentradasalidas;
    }
    
    public void setRelacionentradasalidas(Set relacionentradasalidas) {
        this.relacionentradasalidas = relacionentradasalidas;
    }




}


